config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :orders
  resources :drinks
  resources :foods
  get "/foods/:id/add", to: "foods#add_food", as: "add_food"
  get "/drinks/:id/add", to: "drinks#add_drink", as: "add_drink"
  get "/orders/:id/checkout", to: "orders#checkout", as: "checkout"
  get "/orders/:id/clear_cart", to: "orders#clear_cart", as: "clear_cart"
  get "/orders/:id/checkout_w_card", to:"orders#cardform", as: "cardform"
  get "/foods/:id/remove", to: "foods#remove_food", as: "remove_food"
  get "/drinks/:id/remove", to: "drinks#remove_drink", as: "remove_drink"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/analytics', to: 'users#analytics', as: "analytics"
  resources :cards
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  validates :age, numericality: true
  has_secure_password
    has_many :orders
    has_many :cards
    def fav_order #returns the most ordered meal for a user
      @orders = self.orders
      @orders = @orders.select{|order| order.complete == true}
      @orders = @orders.sort.reverse #sorts by most recent order first
      order_num = 0
      temp_num = 0
      @fav_order = @orders.last
      @orders.each do |order|
        @orders.each do |order2|
          if order.foods == order2.foods && order.drinks == order2.drinks && order != order2 #comparing the contents of the two orders
            temp_num += 1 #tracking how many of the same order there is
          end
        end
        if temp_num >= order_num
          order_num = temp_num
          @fav_order = order
          temp_num = 0
        end
      end
      @fav_order#returning the fav order, which is either the most recent if all orders are the same amount or most ordered.
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :destroy, :edit, :update]
    before_action :user_params, only: [:create]


      # if session.include? :user_id
      #       @cur_user = User.find(session[:user_id])
      #       @order = @cur_user.orders.find do |order|
      #         order.complete == false
      #   end
      #
      #   if !@order
      #       @order = Order.create(complete: false)
      #       if session.include? :user_id
      #       @cur_user.orders << @order
      #       end
      #   end

      def index
        if !logged_in?
          redirect_to login_path
        elsif session.include? :user_id
          @cur_user = current_user
          @order = current_order
        end
        @foods = Food.all
        @drinks = Drink.all
        @users = User.all
    end


    def new
     @user = User.new
    end



    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        redirect_to user_path(@user)
      else
         @errors = @user.errors[:messages]
        render :new
      end
    end



    def show
      if logged_in?
        if current_user.id == params[:id].to_i
          @count = 1
          @orders = @user.orders
          @orders = @orders.select{|order| order.complete}
          @orders = @orders.sort.reverse
        else
          redirect_to root_path
        end
      else
        redirect_to root_path
      end
    end




    def update
      if @user.update(user_params)
        redirect_to @user
      end

    end



    def destroy
      @user.destroy
      redirect_to users_path
    end

    def analytics
      @users = User.all
      @orders = Order.all
      @orders = @orders.select{|order| order.complete == true}
      @order = current_order
      @user = current_user
      @foods = Food.all
      @drinks = Drink.all
      @most_ordered_drink = Order.most_ordered_drink
      @most_ordered_drink_amount = Order.most_ordered_drink_amount
      @most_ordered_food = Order.most_ordered_food
      @most_ordered_food_amount = Order.most_ordered_food_amount
      @average_meal_cost = Order.average_meal_price
      @fav_meal = current_user.fav_order
      @fav_foods = []
      @fav_drinks = []
      @fav_meal.foods.each do |food|
        @fav_foods << food
      end
      @fav_meal.drinks.each do |drink|
        @fav_drinks << drink
      end
    end



    private
    def set_user
     @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:age, :name, :password, :password_confirmation, :username)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div align="center" class="createform">

<%= form_for @user do |f| %>
  Name:       <%= f.text_field :name %><br />
  Username: <%= f.text_field :username %><br />
  Password: <%= f.password_field :password %> <br>
  Confirm Password: <%= f.password_field :password_confirmation %><br>
  Age : <%= f.number_field :age %><br />
  <button type="submit" name="button">Create!</button>
<% end %>
</div>

app/views/users/analytics.html.erb
<%= stylesheet_link_tag "analytics.css" %>
<body class="analyticsbody">

  <div class="jawn">

  <h1 class="analyticsHead">Analytics</h1></div>


<div class="modcard">Most Ordered Drink: <%=link_to @most_ordered_drink.name, @most_ordered_drink%> <br>
    Total Amount Ordered: <%=@most_ordered_drink_amount%></div>
    <br>
    <div class="modcard">Most Ordered Meal: <%=link_to @most_ordered_food.name, @most_ordered_food%> <br>
        Total Amount Ordered: <%=@most_ordered_food_amount%></div><br>
        <div class="modcard">Average Meal Cost: <%='%.2f' % @average_meal_cost%></div><br>
        <div class="modcard"><%=current_user.name%>'s Favorite Meal: <br>
            Foods:
            <%@fav_foods.each do |food|%>
            <%=food.name%>
            <%end%>
            <br>Drinks:
            <%@fav_drinks.each do |drink|%>
            <%=drink.name%>
            <%end%>
        </div>

        </body>

app/views/users/edit.html.erb
<%= stylesheet_link_tag "userlogin.css" %>
<h1>Edit User</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<%= stylesheet_link_tag "index.css" %>

<body class="mainpage">



<h1 id = "foodheader">Food: </h1>

<br><br>
<div class="foods">

<%@foods.each do |food|%>
<br>







<div class="menucard">


<%= link_to food.name, food %>
<p class="price"><%='%.2f' % food.price.to_d %> each </p>
<%=link_to image_tag(url_for(food.imgurl)), food%><br>
<%= link_to "Add to Order", add_food_path(food) %>

<br>
</div>


<%end%>
</div>

<br><br>

<h1 id = "drinkheader">Drinks: </h1>

<br><br><br>
<div class="drinks">

<%@drinks.each do |drink|%>
<br>



<div class="menucard">


<%= link_to drink.name, drink %>
<p class="price"><%='%.2f' %  drink.price.to_d %> each </p>

<%=link_to image_tag(url_for(drink.imgurl)), drink%><br>
<%= link_to "Add to Order", add_drink_path(drink) %>

<br>
</div>

<%end%>
</div>

</body>

app/views/users/new.html.erb
<%= stylesheet_link_tag "userlogin.css" %>
<body class="createbody">

<div class="jawn">


<h1 class="createpage">Create New User</h1>
</div>
    <%= render 'form' %>
</body>

app/views/users/show.html.erb
<%= stylesheet_link_tag "usershow.css" %>

<body class="usershowpage">


<h1>Welcome <%=@user.name%> !</h1>
<%if current_order_exists?%>
<h4><%=link_to "Return to Menu for Current Order", users_path%></h4>
<%else%>
<h4><%=link_to "Create a New Order", users_path%></h4>
<%end%>



<ul>


  <%if @orders.length > 0%>

    <%@orders.each do |order|%>

<div class="profilecard">


    <h2>Order #<%= @count %></h2>
      <%if order.drinks.length > 0%>
      <h3>Drinks: </h3>
      <%end%>
       <%order.drinks.each do |drink| %>
        <li><%= drink.name%>
          <%end%></li>
          <%if order.foods.length > 0%>
          <h3>Food: </h3>
          <%end%>
      <%order.foods.each do |food| %>
        <li><%= food.name%>
      <%end%></li>


      <% @count += 1 %>
      </div>
    <%end%>

  <%else%>


  <div class="profilecard">


    <h2>No Past Orders On Record</h2>
</div>

  <%end%>


</ul>


<%= link_to "Delete",@user, method: :delete %>
<%= link_to "Edit User", edit_user_path(@user) %>
</body>