config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :orders
  resources :drinks
  resources :foods
  get "/foods/:id/add", to: "foods#add_food", as: "add_food"
  get "/drinks/:id/add", to: "drinks#add_drink", as: "add_drink"
  get "/orders/:id/checkout", to: "orders#checkout", as: "checkout"
  get "/orders/:id/clear_cart", to: "orders#clear_cart", as: "clear_cart"
  get "/orders/:id/checkout_w_card", to:"orders#cardform", as: "cardform"
  get "/foods/:id/remove", to: "foods#remove_food", as: "remove_food"
  get "/drinks/:id/remove", to: "drinks#remove_drink", as: "remove_drink"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/analytics', to: 'users#analytics', as: "analytics"
  resources :cards
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :food_orders
    has_many :foods, through: :food_orders
    has_many :drink_orders
    has_many :drinks, through: :drink_orders
    belongs_to :user
    def self.complete_orders #returns all orders that are complete
        @orders = self.all
        @orders = @orders.select{|order| order.complete == true}
    end
    def self.most_ordered_food_amount #returns the most ordered food amount as an integer from all orders
        @orders = self.complete_orders
        @foods = Food.all
        @highest_count =  0
        temp_highest_count = 0
        @foods.each do |food|
            @orders.each do |order|
                if order.foods.include? food
                    arr = order.foods.select{|innerfood| innerfood.name == food.name}
                    temp_highest_count += arr.length
                end
            end
            if temp_highest_count > @highest_count
                @highest_count = temp_highest_count
                temp_highest_count = 0
            else
                temp_highest_count = 0
            end
        end
        @highest_count
    end
    def self.most_ordered_food #returns the most ordered food object
        @orders = self.complete_orders
        @foods = Food.all
        @highest_count =  0
        temp_highest_count = 0
        @foods.each do |food|
            @orders.each do |order|
                if order.foods.include? food
                    arr = order.foods.select{|innerfood| innerfood == food}
                    temp_highest_count += arr.length
                end
            end
            if temp_highest_count > @highest_count
                @highest_count = temp_highest_count
                @food = food
                temp_highest_count = 0
            else
                temp_highest_count = 0
            end
        end
        @food
    end
    def self.most_ordered_drink_amount #returns the most ordered drink amount as an integer from all orders that are complete
        @orders = self.complete_orders
        @drinks = Drink.all
        @highest_count =  0
        temp_highest_count = 0
        @drinks.each do |drink|
            @orders.each do |order|
                if order.drinks.include? drink
                    arr = order.drinks.select{|innerdrink| innerdrink.name == drink.name}
                    temp_highest_count += arr.length
                end
            end
            if temp_highest_count > @highest_count
                @highest_count = temp_highest_count
                temp_highest_count = 0
            else
                temp_highest_count = 0
            end
        end
        @highest_count
    end
    def self.most_ordered_drink #returns the most ordered drink object from complete orders
        @orders = self.complete_orders
        @drinks = Drink.all
        @highest_count =  0
        temp_highest_count = 0
        @drinks.each do |drink|
            @orders.each do |order|
                if order.drinks.include? drink
                    arr = order.drinks.select{|innerdrink| innerdrink == drink}
                    temp_highest_count += arr.length
                end
            end
            if temp_highest_count > @highest_count
                @highest_count = temp_highest_count
                @drink = drink
                temp_highest_count = 0
            else
                temp_highest_count = 0
            end
        end
        @drink
    end
    def total_price #total price of a single order
        @total_price = 0.0
        self.foods.each do |food|
            @total_price += food.price
        end
        self.drinks.each do |drink|
            @total_price += drink.price
        end
        @total_price
    end
    def self.average_meal_price #analytics of average meal cost for all orders.
        @total = 0.0
        @orders = self.complete_orders
        @orders.each do |order|
            @total += order.total_price
        end
        @avg_price = @total / @orders.length
    end
   
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def show
        if !logged_in?
            redirect_to root_path
        end
        @order = Order.find(params[:id])
        if current_user.orders.include? @order
            @foods = @order.foods
            @drinks = @order.drinks
            @total_price = @order.total_price
        else
            redirect_to root_path
        end
    end
    def checkout

        @order = Order.find(params[:id])
        if !@order.drinks.all.empty? || !@order.foods.all.empty?
            @order.complete = true
            @order.save
            redirect_to user_path(current_user)
        else
            flash[:error] = "Cannot checkout with an empty cart"
            redirect_to users_path
        end

    end

    def cardform
      render :creditcardform
    end
    
    def clear_cart
        @order = Order.find(params[:id])
        while !@order.drinks.all.empty?
            @order.drinks.clear
        end
        while !@order.foods.all.empty?
            @order.foods.clear
        end
        redirect_to order_path(@order)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/creditcardform.html.erb
<body class="checkoutform">

<h2>Checkout Form</h2>
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">
            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <h4 id="checkout"><%=link_to "CHECKOUT", checkout_path %></h4><br>
        <h4 id="checkout"><%= link_to "BACK", order_path %></h4>

      </form>
    </div>
  </div>

  </body>

app/views/orders/show.html.erb
<%= stylesheet_link_tag "orders.css" %>


<body id="cartform">

<div class="jawn">


  <div class="col-25">
    <div class="container">
      <h4>Cart <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b><%= @drinks.length + @foods.length %></b></span></h4>

      <div id="drinks">
        <h3>Drinks: </h3>
        <%@drinks.each do |drink|%>
        <li><%=link_to drink.name, drink%>
          <%= '%.2f' % drink.price.to_d%><br>
        </li>
        <%end%>
      </div>

      <div id="foods">
        <h3>Food: </h3>
        <%@foods.each do |food|%>
        <li>
          <%=link_to food.name, food%>
          <%= '%.2f' % food.price.to_d%><br>
        </li>
        <%end%>
      </div><br>
      <div class="addmore"><%=link_to "Add More to Order", users_path%></div>
      <div class="clearcart"><%=link_to "Clear Cart", clear_cart_path%></div>


      <hr>
      <p>Total <span class="price" style="color:black"><b><%= '%.2f' % @total_price %></b></span></p>
    </div>
    <div class="checkoutwcard">
    <h4 id="checkout"><%=link_to "Pay with Cash!", checkout_path %></h4>

    <h4 id="checkout"><%=link_to "Pay with Card!", cardform_path %></h4></div>
  </div>
  </div>

</body>