config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :orders
  resources :drinks
  resources :foods
  get "/foods/:id/add", to: "foods#add_food", as: "add_food"
  get "/drinks/:id/add", to: "drinks#add_drink", as: "add_drink"
  get "/orders/:id/checkout", to: "orders#checkout", as: "checkout"
  get "/orders/:id/clear_cart", to: "orders#clear_cart", as: "clear_cart"
  get "/orders/:id/checkout_w_card", to:"orders#cardform", as: "cardform"
  get "/foods/:id/remove", to: "foods#remove_food", as: "remove_food"
  get "/drinks/:id/remove", to: "drinks#remove_drink", as: "remove_drink"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/analytics', to: 'users#analytics', as: "analytics"
  resources :cards
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :food_orders
    has_many :orders, through: :food_orders
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :add_food, :remove_food]

    def index

    end
    def add_food
        if logged_in?
            @cur_user = current_user
            @order = current_order
            @order.foods << @food
            redirect_to users_path
        end
    end

    def remove_food
      if logged_in?
          @cur_user = current_user
          @order = current_order
          @order.foods.delete(@food)
          redirect_to order_path(@order)
      end
    end

    private

    def set_food
      @food = Food.find(params[:id])
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/show.html.erb
<%= stylesheet_link_tag "drinkshow.css" %>

<body class="drinkshow">



<div class="card">

<h1><%=@food.name%></h1>
<%=image_tag(url_for(@food.imgurl))%>

<p><%= @food.desc %></p>

<p class="price"></p>Price Per Food: <%='%.2f' %  @food.price%>






<% if current_order.foods.include? @food%>
<%= link_to "remove from order", remove_food_path(@food) %>
<%end%>
<%= link_to "add to order", add_food_path(@food) %>
</div>
</body>