config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :orders
  resources :drinks
  resources :foods
  get "/foods/:id/add", to: "foods#add_food", as: "add_food"
  get "/drinks/:id/add", to: "drinks#add_drink", as: "add_drink"
  get "/orders/:id/checkout", to: "orders#checkout", as: "checkout"
  get "/orders/:id/clear_cart", to: "orders#clear_cart", as: "clear_cart"
  get "/orders/:id/checkout_w_card", to:"orders#cardform", as: "cardform"
  get "/foods/:id/remove", to: "foods#remove_food", as: "remove_food"
  get "/drinks/:id/remove", to: "drinks#remove_drink", as: "remove_drink"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/analytics', to: 'users#analytics', as: "analytics"
  resources :cards
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="navbar">
    <%= link_to "Home", root_path %>
    <% if !logged_in?%>
      <%= link_to "Create New Account", new_user_path %>
      <%= link_to "Login" , login_path %>
    <%else%>
      <%= link_to "Logout", logout_path%>
      <%= link_to "#{current_user.name} Profile", current_user%>
      <%= link_to "Current Order", order_path(current_order) %>
      <%= link_to "Analytics", analytics_path%>
    <%end%>
    </div>

    <div class="spacer">
      &nbsp;

    </div>
    <%= yield %>

</html>